### ISSUE TITLE
Rename TestCaseContext's names...

### ISSUE THREAD

**Issue by sean-** [ovh/venom#126]
This is going to be part of a larger imminent PR, but opening an issue to track:

- Rename `TestCaseContext`'s `Init()` method to `SetupStep()`
- Rename `TestCaseContext'`s `Close()` method to `TeardownStep()`

Change approved by @yesnault on Gitter.

**Comment by yesnault** [comment]
fixed on https://github.com/ovh/venom/commit/47441c3f614fbe9b1aaa121aae611d3bf1b4c16e
