### ISSUE TITLE
ShouldBeIn fails with: Expected '[1,2]' to be in the container (string), but it wasn't!

### ISSUE THREAD

**Issue by neyaled** [ovh/venom#138]
We are trying to check if an array contain a set of expected values.

The assertions are:
    assertions:
    - result.statuscode ShouldEqual 200 
    - result.body ShouldBeIn 1
    - result.body ShouldBeIn 2

The assertions on the body fail.

Logs are:

assertion: result.body ShouldBeIn 2
Expected '[1,2]' to be in the container (string), but it wasn't!
result.body: [1,2]
result.bodyjson.bodyjson0: 1
result.bodyjson.bodyjson1: 2

As the order of the array could change (by adding more tests before or else) we prefer not to depend
on the order of the array.

**Comment by yesnault** [comment]
```
❯ cat foo.yml
name: Foo
testcases:
  - name: TestAssertions
    steps:
    - script: echo 1
      assertions:
      - result.systemoutjson ShouldBeIn 1 2
❯ venom run foo.yml
 • Foo (foo.yml)
 	• TestAssertions SUCCESS
