### ISSUE TITLE
feat(http/executor): ability to inspect http request and response payloads

### ISSUE THREAD

**Issue by titpetric** [ovh/venom#219]
I expected more info when running with `--log=debug` flags.

- No output what is sent (headers) or requested (URL)
- No output what was received (headers, body/json)

I'd even like this to be per-step, as you'd usually be doing this when implementing a step. I'll issue a request and then filter out the data with various assertions: until I'm satisfied and can move on to the next one.

The go stdlib provides [net/http/httputil](https://golang.org/pkg/net/http/httputil) with DumpRequest/DumpResponse functions in case this flag would be provided.

If you're interested I can field the PR for this.

**Comment by titpetric** [comment]
Somewhat of a work around: `--log=debug` and a step to echo the response body:

~~~yaml
- script: echo '{{.TestName.result.body}}`
~~~

**Comment by yesnault** [comment]
Hi, yes, we probably can do better with the flag --log=debug. BTW, this should be implemented on the refactor branch https://github.com/ovh/venom/tree/refactor and not on master branch.
