### ISSUE TITLE
feat(http/executor): replace variables in bodyFile contents

### ISSUE THREAD

**Issue by titpetric** [ovh/venom#220]
The string read with `bodyFile` directive stays as-is, template variables are not replaced

**Comment by nqb** [comment]
Hi,

I'm not able to make it work `bodyFile` directive using `http` executor. Is this what you mean ?

**Comment by nqb** [comment]
I'm interested by this feature too.

**Comment by titpetric** [comment]
Correct, closing this issue as a duplicate
