### ISSUE TITLE
feat(executors/echo): don't worry about quoting when printing vars

### ISSUE THREAD

**Issue by titpetric** [ovh/venom#221]
Depending if you have various quotes (e.g. ' or ") in the content, it becomes a bother escaping them. Instead of resorting to exec for printing and for filters (e.g. `{{ var | escape }}`), I suggest:

- an executor like `echo` which just takes a value and prints it (e.g. `fmt.Println(value)`)
- optionally add formatting vars, with features closer to fmt.Printf

It also has the benefit of not running an exec stdcall, not that it's a big impact in CI jobs.

~~~yaml
format: %s %d %q
vars:
  - var1
  - var2
  - var3
~~~

I'm not sure that I need to mark the vars with `{{ var1 }}` and such, the template tags seem redundant in this case, but I'm not sure if it's a requirement.

**Comment by fsamin** [comment]
in the commit 47441c3 we add a new `info` keyword available at every steps that may help you to print some variable values.
you will find some example on https://github.com/ovh/venom/blob/master/tests/exec.yml
