### ISSUE TITLE
Chrome browser not working with Venom 

### ISSUE THREAD

**Issue by kevinramage** [ovh/venom#223]
Hello,

I work with Venom in web context and I want be able to run some GUI tests.
When I run tests, Venom can't initialize a session, I have this error message:

Starting ChromeDriver 78.0.3904.105 (60e2d8774a8151efa6a00b1f358371b1e0e07ee2-refs/branch-heads/3904@{#877}) on port
1097
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
**failed to navigate: request unsuccessful: invalid session id**

I try to get the last venom version (v0.27.0), I have the same issue.

Do you have any solution for this issue ?

Regards

**Comment by kevinramage** [comment]
Hello,
To fix this issue, we need to impact agouti code. I create a pull request on agouti project.
https://github.com/sclevine/agouti/pull/194
It's not a venom issue, it's an agouti issue

Regards,

**Comment by yesnault** [comment]
@kevinramage ok, thank you!
