### ISSUE TITLE
Compilation issue with fixtures import

### ISSUE THREAD

**Issue by kevinramage** [ovh/venom#224]
Hello,

I want to contribute on this project and I'm not able to compile the project.
I run the following command:
go get github.com/ovh/venom
go get ./...
go install github.com/ovh/venom/cli/venom

And I have this result:
src\github.com\ovh\venom\executors\dbfixtures\executor.go:9:2: code in directory src\github.com\go-testfixtures\testfixtures expects import "github.com/go-testfixtures/testfixtures/v3"

Do you have a solution for this issue ?

Regards,

**Comment by yesnault** [comment]
Hi @kevinramage ,

With go >= 1.13

Can you try : 

```bash
$ go version
go version go1.13.4 darwin/amd64

$ git clone git@github.com:ovh/venom.git
$ cd venom/cli/venom
$ go build
$ ./venom -h
```

Feel free to reopen if needed.
