### ISSUE TITLE
bug: venom update is not idempotent

### ISSUE THREAD

**Issue by nqb** [ovh/venom#239]
When you have latest `venom` version on your system and you try to update using `venom update`, `venom` is updated.

### Steps to reproduce
1. Install latest version of venom
2. Run venom update

### Actual results
Venom is updated.

### Expected results
Venom should compare current version with version available on GitHub and update only if it's necessary.

**Comment by nqb** [comment]
I still have the issue when running version: v1.0.0-beta.2

**Comment by yesnault** [comment]
I'll recheck

**Comment by yesnault** [comment]
Fixed with v1.0.0-beta4
