### ISSUE TITLE
question: share variables between test suites

### ISSUE THREAD

**Issue by nqb** [ovh/venom#240]
Hello,

I would like to know if it possible to share variables between test suites. I didn't find anything related to this in documentation.

My use case:
1. I run MyTestSuite1.yml and register a variable from http executor during step 'get-login-token'
1. I want to reuse this variable in MyTestSuite2.yml using `{{.get-login-token.myvariable}}`

I did some tests and was not able to make it work using only `testcase` name.

A possible workaround is to write variable in a JSON or YAML file and call `venom` a second time using ` --var-from-file`

**Comment by yesnault** [comment]
Hi, no sorry, it's not possible. You can write the variable in a temp file, and read the file from other testsuite.

**Comment by nqb** [comment]
Thanks for your answer @yesnault, I will open a feature request.
