### ISSUE TITLE
feat: share variables between test suites

### ISSUE THREAD

**Issue by nqb** [ovh/venom#241]
As mentioned in #240, it would be nice if we can share "on the fly" variables between test suites.

My use case:
1. I run `MyTestSuite1.yml` and register a variable from `http` executor during step 'get-login-token'
1. I want to reuse this variable in `MyTestSuite2.yml` using `{{.get-login-token.myvariable}}`

Current workarounds:
- write variable in a temp file and read it using `read` executor
- write variable in a JSON or YAML file and call `venom` a second time using ` --var-from-file`

**Comment by yesnault** [comment]
it's not really possible to share "on the fly": it's possible to run testsuite in parallel, this is not link possible (outside the workarounds) to do a live sharing computed by venom. 
Personally, I prefer to keep the total isolation between each testsuite in the a core venom engine.

**Comment by yesnault** [comment]
workarounds listed are the right way to do that.
