### ISSUE TITLE
Assertions on null JSON values

### ISSUE THREAD

**Issue by benoitmasson** [ovh/venom#265]
Hi,

Given the following `bodyjson` content:
```json
{
  "foo": null
}
```
I would like to make an assertion about this `null` value, something like `result.bodyjson.foo ShouldBeNil`.

However, the only assertion which works is `result.bodyjson.foo ShouldEqual ""`, as if deserializing the body had replaced my `null` object with an empty string. Is there something better I can do to match against this `null` value?

Note: this is probably similar to issue #262. I guess that deserializing the JSON object without knowing the object schema can lead to strange results when encountering zero-values.
In my case, I'm wondering whether there would be a `__type__` alternative which could help.

**Comment by kevinramage** [comment]
**Reproduced with the following code:**
name: "Test venom"
testcases:
  - name: "httpGet"
    steps:
      - type: http
        method: GET
        url: "http://127.0.0.1:8081"
        assertions:
          - "result.bodyjson.id ShouldBeNil"

**Diagnostic:**
(assertion.go line 146)
When we try to retrieve actual value in assertion.go, we use the executorResult object to get the value id of result.bodyjson, the result is an empty value.

_actual, ok := executorResult[assert[0]]
fmt.Printf("BodyJSON: %+v\n", executorResult["result.bodyjson"])
fmt.Printf("BodyJSON.id: %+v\n", executorResult["result.bodyjson.id"])
=>
BodyJSON: map[id:\<nil\>]
BodyJSON.id:_

But if we store the BodyJSON in Map object, I don't have the same behaviour

_actual, ok := executorResult[assert[0]]
var test map[string]interface{} = (executorResult["result.bodyjson"]).(map[string]interface{})
fmt.Printf("Map: %+v\n", test)
fmt.Printf("Map.id: %+v\n", test["id"])
=>
Map: map[id:\<nil\>]
Map.id: \<nil\>_

So to fix the issue, we must change the way to retrieve the actual value.  
This change must be apply only for map object like result.bodyjson.

**Comment by fsamin** [comment]
Hello @kevinramagen, which version did you test with?

**Comment by kevinramage** [comment]
Hello @fsamin , I test with the venom master branch and the go version "go1.14 windows/amd64".
I try to test with the assertions refacto version "fsamin/refactor/1", I reproduce the issue (result.bodyjson.id is nil but actual value is empty):

.\venom.exe run .\bug-265.yml --log debug
BodyJSON: map[id:<nil>]
BodyJSON.id: 
Map: map[id:<nil>]
Map.id: <nil>
FAILURE .\bug-265.yml   0.02s

FAILED Test venom [.\bug-265.yml]
        Failure in ".\\bug-265.yml":9
        Testcase "httpGet", at step 0
        Assertion "result.bodyjson.id ShouldBeNil" failed. expected: Nil but is wasn't

**Comment by fsamin** [comment]
it's fixed in 47441c3
eg. https://github.com/ovh/venom/blob/master/tests/http.yml#L12
