### ISSUE TITLE
Assertion ShouldBeLessThan fails

### ISSUE THREAD

**Issue by LuisHudson25** [ovh/venom#267]
Hello,

It seems that ShouldBeLessThan assertion is not working.

I'm using venom v0.27.0 and the following example:
`version: "2"

name: Test Assertions

testcases:
- name: TestAssertions
  steps:
  - script: echo 3
    assertions:
    - result.systemout ShouldBeGreaterThan 1
    - result.systemout ShouldBeLessThan 10`

I get the error: "Expected '3' to be less than '10'".
I'm not very good in maths, but I think there is a problem here :-)

I tried to use the function go assertions.ShouldBeLessThan and it's working as expected so I think it comes from the venom integration.

Thanks for this wonderful tool.
Luis

**Comment by kevinramage** [comment]
Hello,

I reproduce the issue and the issue come from smartystreets/assertions module.
When you compare 2 strings with assertions module, comparison is an alphabetical comparison and in alphabetical order 3 is before 1 (less_than.go line 114)
So the assertion "result.systemout ShouldBeLessThan 10" failed and the assertion "result.systemout ShouldBeLessThan 9" passed.
To resolve the issue, you must parse the string before send it to assertions module.
To do it:
- create a wrapper function to parse the string to integer and call assertions function after
- register the wrapper function on assertMap map object (assertion.go line 269).

I'm not Venom product owner but I think this solution is acceptable ? @yesnault 

Regards

**Comment by yesnault** [comment]
@kevinramage yes, it's the solution

**Comment by kevinramage** [comment]
I create PR-278 to fix the issue

**Comment by yesnault** [comment]
Fixed on master with https://github.com/ovh/venom/commit/47441c3f614fbe9b1aaa121aae611d3bf1b4c16e

![Capture d’écran 2020-11-17 à 13 59 05](https://user-images.githubusercontent.com/395454/99393141-3232b700-28dd-11eb-9aaa-3a4a9df97c14.png)

**Comment by LuisHudson25** [comment]
Great, thank you both of you !
