### ISSUE TITLE
Kafka Avro executor

### ISSUE THREAD

**Issue by fabriziomoscon** [ovh/venom#287]
Hi @yesnault thank you for the great tool!
I was wondering if there is a plan to extend the kafka executor to be able to publish and verify Avro encoded messages.

In any case, it would be good if yourself and @marcaudefroy could give me some directions on a possible PR that I could submit to contribute this feature. Do you think it is possible? How would you go about solving it... that kind of directions.

Thank you

**Comment by fsamin** [comment]
done (b741e2c)
