### ISSUE TITLE
Kafka & panic: non-positive interval for NewTicker

### ISSUE THREAD

**Issue by dimitri123456** [ovh/venom#366]
Using:
go get -u github.com/ovh/venom
When i add test using Kafka:
`   - type: kafka
      clientType: consumer
`
Some test are ok because they don't use Kafka, but my 04-mytest.yml fail and display:
... 
[INFO] SUCCESS ./integration-test/venom/tests/03-mytest.yml 62.587076ms
[WARN] panic: non-positive interval for NewTicker
[WARN] 
[WARN] goroutine 362 [running]:
[WARN] time.NewTicker(0x0, 0x8e33ff)
[WARN] 	/usr/local/go/src/time/tick.go:23 +0x147
[WARN] github.com/bsm/sarama-cluster.(*Consumer).cmLoop(0xc0001a4000, 0xc000102540)
[WARN] 	/go/pkg/mod/github.com/bsm/sarama-cluster@v2.1.15+incompatible/consumer.go:452 +0x5a
[WARN] github.com/bsm/sarama-cluster.(*loopTomb).Go.func1(0xc0006fa400, 0xc0002bee60)
[WARN] 	/go/pkg/mod/github.com/bsm/sarama-cluster@v2.1.15+incompatible/util.go:73 +0x7b
[WARN] created by github.com/bsm/sarama-cluster.(*loopTomb).Go
[WARN] 	/go/pkg/mod/github.com/bsm/sarama-cluster@v2.1.15+incompatible/util.go:69 +0x66
[INFO] Test venom failed

**Comment by yesnault** [comment]
stacktrace indicates that the version used is < 1.0.0. It's fixed with venom > 1.0.0-rc.
