### ISSUE TITLE
Feat: Display assertions errors for user_executor

### ISSUE THREAD

**Issue by manzan46** [ovh/venom#375]
ℹ️ backport from: #369 

When a user executor assertions failed, in the output, we just get a FAILURE message but not the assertion failure as we have for teststep, so we have to dig in the log.

Having something like ⬇️  (but better formatted 🙈 ) would be really helpful

![image](https://user-images.githubusercontent.com/1071962/109950402-c08c4680-7cdc-11eb-8a34-b2db3aaae084.png)

**Comment by yesnault** [comment]
Thank you, I'll take a look on it.
