### ISSUE TITLE
testsuite variable behavior change after #367

### ISSUE THREAD

**Issue by manzan46** [ovh/venom#377]
👋🏻  Something seems to have changed with variables of test suite after the merge of https://github.com/ovh/venom/pull/367, not sure if it was intentional or not: 

for the following testsuite

```
name: testsuite
vars:
  phone_number: "+3375{{ randNumeric 7 }}"
testcases:
- name: test 1
  steps:
  - type: exec
    script: echo '{{.phone_number}} test 1'
    info: '{{.phone_number}} test 1'
- name: test 2
  steps:
  - type: exec
    script: echo '{{.phone_number}} test 2'
    info: '{{.phone_number}} test 2'
```

here is what happen first run is with current master (bc5ffe8df9d93b0fd68a0931683f6f5e2ac095a3), second run was with before #367 merge: 

```
> venom run mytc.yml -v                                                                                     
 • testsuite (mytc.yml)
 	• test-1 SUCCESS
	  [info] +33751560545 test 1 (mytc.yml:9)
 	• test-2 SUCCESS
	  [info] +33758282547 test 2 (mytc.yml:14)
> .venom mytc.yml - -v                                                                                    
 • testsuite (mytc.yml)
 	• test-1 SUCCESS
	  [info] +33759344279 test 1 (mytc.yml:9)
 	• test-2 SUCCESS
	  [info] +33759344279 test 2 (mytc.yml:14)
```

As you can see on the first run the variable is interpolated at each step, whereas at the second one, it's interpolated only once, IMO it would be more logic to keep it as it was, only testsuite interpolated variables at start of TC.

**Comment by yesnault** [comment]
@manzan46 you are right, the variable should be evaluated only once. Thank you for this report, the #367 contains a lot of fixes but also some unexpected  behavior.
