### ISSUE TITLE
Possibility to change the working directory

### ISSUE THREAD

**Issue by adrienaury** [ovh/venom#400]
Hi 👋 

Currently, test suites are executed in the folder containing the test suite YAML definition.

There is a use case where we want to execute a test suite in a different folder. It doen't seem to be possible to change it.

I tried:

```console
venom run --var venom.testsuite.workdir=workdir suites/errors.yml
```

But `panic: runtime error: invalid memory address or nil pointer dereference`

Tested version : v1.0.0-rc.4

**Comment by yesnault** [comment]
Hi,

No, it's not possible to update the workdir. Venom uses as basepath the testsuite file. 
But, you can rework a little your testsuite files location, (cf. comment https://github.com/ovh/venom/pull/398#issuecomment-829235952) to have a common workdir for some testsuites.
