### ISSUE TITLE
Question: how to handle json array where elements might be at random sort order

### ISSUE THREAD

**Issue by guoweis-outreach** [ovh/venom#416]
Hi,

I have a response where there is a json array, 
```json
"bodyjson": {
  "events": [
    {"event":{"value":3}},
    {"event":{"value":4}}
  ]
}
```

How do I assert that there must be 2 events, one with value 3 and the other value 4?

**Comment by yesnault** [comment]
No sort available, you probably need to write a step script to do this check with jq binary for example.
