### ISSUE TITLE
Question: can we have more example on Variable helpers?

### ISSUE THREAD

**Issue by guoweis-outreach** [ovh/venom#418]
For example, I can't tell how to do substr. :) No reference in the code either when I did a string search

**Comment by nqb** [comment]
If I'm not wrong the helpers are the same as for [CDS](https://ovh.github.io/cds/docs/concepts/variables/#helpers) starting from Venom 1.0.0

**Comment by yesnault** [comment]
yes, we should add some doc about that. 

For now, there are some examples on https://ovh.github.io/cds/docs/concepts/variables/#helpers

**Comment by guoweis-outreach** [comment]
is there any way to remove a trailing "/n" or is there any way to extend these helpers?

**Comment by yesnault** [comment]
You can't extend these helpers, but you can try to use replace, something like that `{{.foo | replace "\n" "."}}`

**Comment by guoweis-outreach** [comment]
can you give an example how to do substr?

**Comment by guoweis-outreach** [comment]
nvm, figured it out. substr <beginingindex> <endingindex>

**Comment by fsamin** [comment]
to remove the first 36 chars, you should try something like {{ .foo | substr 36 -1 }}
