### ISSUE TITLE
feat: write results in separate files

### ISSUE THREAD

**Issue by nqb** [ovh/venom#441]
When you use Venom on one system to run several test suites one by one, `venom.log` and `test_results.XX` are overwritten by latest test suite.

### Steps to reproduce

```console
# cat a.yml 
name: a
version: 2
testcases:
- name: a
  steps:
  - type: exec
    script: echo 'a'

# cat A.yml 
name: A
version: 2
testcases:
- name: A
  steps:
  - type: exec
    script: echo 'A' 
```
Run test suite one by one:
```
venom run -v --output-dir=results a.yml
venom run -v --output-dir=results A.yml
```

### Actual results
`results/test_results.xml` and `results/venom.log` contains results from `A.yml`

### Expected results
`results` directory contains results for `a.yml` and `A.yml`

### Workaround
Run test suite at same time using `venom run a.yml A.yml`

**Comment by yesnault** [comment]
venom should create different file. test_result_a.xml and test_result_A.xml, same with venom.log file

**Comment by nqb** [comment]
Agree with your solution @yesnault 👍
