### ISSUE TITLE
bug: value of a variable generated through an helper is not consistent

### ISSUE THREAD

**Issue by nqb** [ovh/venom#445]
If I use a helper `randAlpha` to initialize a variable in a dedicated file (used with `--var-from-file` option), value of my variable is not consistent across the testsuite.

### Steps to reproduce

```console
# cat > e.yml << EOF
---
name: e
version: 2
testcases:
- name: myvar_first
  steps:
  - type: exec
    script: "echo myvar first time: {{.myvar}}"
    info: "{{.result.systemout}}"

- name: myvar_second
  steps:
  - type: exec
    script: "echo myvar second time: {{.myvar}}"
    info: "{{.result.systemout}}"
EOF

# cat > vars.yml <<EOF
---
myvar: '{{ randAlpha 3 }}'
EOF

```
### Actual results

```console
# venom run e.yml --var-from-file vars.yml 
 • e (e.yml)
 	• myvar_first SUCCESS
	  [info] myvar first time: CBq (e.yml:8) (e.yml:8)
 	• myvar_second SUCCESS
	  [info] myvar second time: cjB (e.yml:14) (e.yml:14)
```

### Expected results
I expect `myvar` to have the same value from beginning to end of test suite.

If variable declaration is done at beginning of testsuite like this:

```console
# cat > e.yml << EOF
---
name: e
vars:
  myvar: '{{ randAlpha 3 }}'
version: 2
testcases:
- name: myvar_first
  steps:
  - type: exec
    script: "echo myvar first time: {{.myvar}}"
    info: "{{.result.systemout}}"

- name: myvar_second
  steps:
  - type: exec
    script: "echo myvar second time: {{.myvar}}"
    info: "{{.result.systemout}}"
EOF
```

Value of `myvar` is consistent from beginning to end of test suite.

I also noticed some weird behaviors if I initialize another variable with value of this variable like: `myvar2: '{{.myvar}}'`

**Comment by nqb** [comment]
Hello @fsamin and @yesnault,

I saw you are working actively on Venom at the moment.
Could you tell me if my usage of helper is wrong here or it's a bug ?

**Comment by yesnault** [comment]
Hi @nqb your usage is ok, there is a bug, the vars files should be interpolated only once.
