### ISSUE TITLE
feat: provide possibility for HTTP bearer token authentication

### ISSUE THREAD

**Issue by AresSec** [ovh/venom#446]
Hi,
would it be possible to add to the HTTP executor also the possibility to add an Authoriztation bearer token (https://datatracker.ietf.org/doc/html/rfc6750) ? At the moment only Authorization basic tokens are possible and many modern web applications are using OAuth for authentication.

**Comment by fsamin** [comment]
Hi,

Did you try to a header such as `Authorization: Bearer xxxxxxx` ?
