### ISSUE TITLE
Assertion to cookie's properties

### ISSUE THREAD

**Issue by righettod** [ovh/venom#499]
Hi,

There is a keyword to access to a specific cookie's properties from a `Set-Cookie` response header ? 

The goal is to be able to perform assertions on a issued cookie like for example the presence of the `Secure`, `HttpOnly`, `SameSite` attributes, for example, in a context of post deployment security validations.

I have read the documentation of the **http** executor but I only found access to headers. 

I apologize in advance if I have missed the documentation part where it is described.

Thank you very much in advance 😃

**Comment by kevinramage** [comment]
Hello,

You can find in attachment an example of header assertion.
[test.txt](https://github.com/ovh/venom/files/8180864/test.txt)

You can use this syntax to check an header: result.headers.set-cookie ShouldContainSubstring secure
Header key must be in lower case.

Regards,

**Comment by righettod** [comment]
Thank you very much 😃
