### ISSUE TITLE
interpolation fails

### ISSUE THREAD

**Issue by amlwwalker** [ovh/venom#501]
Having same issue as this PR here https://github.com/ovh/venom/pull/410

can this be reviewed, merged as it causes a fatal issue with the v1.0.1 version that makes it unusable

EDIT: Is there some documentation on the use of interpolation of body files and why it occurs/why you would want interpolation enabled?

**Comment by nqb** [comment]
Hi,

Perhaps it has been solved by https://github.com/ovh/venom/pull/481

**Comment by lucaspichi06** [comment]
Hi! We saw the preserve_bodyfile flag, but it seems like it is not included in any release yet. I saw it in the master branch but it is not tagged. I don't even see it in the new beta release. Is that right?

**Comment by nqb** [comment]
Yes, you're right @lucaspichi06

**Comment by lucaspichi06** [comment]
Okay. Are you planning to include it in some release soon?
