### ISSUE TITLE
Adding time values to {{.venom.datetime}}

### ISSUE THREAD

**Issue by amlwwalker** [ovh/venom#512]
What level of templating is possibly within the yml files?

For instance can we call on other standard capabilities within templating?

I am trying to set an expiry 1 hour into the future, and short of hardcoding it, I thought it may in some way be possible to use the templating engine?

I wondered about something like `{{ ((time.Now).Add (time.Hour 1)) }}'` but the equivalent using the `.venom.datetime`

**Comment by ivan-velasco** [comment]
Does this help?
https://github.com/ovh/venom/pull/711

**Comment by yesnault** [comment]
I think yes, feel free to reopen @amlwwalker .
