### ISSUE TITLE
Web executor -  invalid session id

### ISSUE THREAD

**Issue by kevinramage** [ovh/venom#518]
When we try to use web actions, we have this error message: "invalid session id".
https://github.com/ovh/venom/discussions/515
After check the worflow, you can view this error during the session creation: "invalid argument: cannot parse capability: chromeOptions\nfrom invalid argument: cannot parse args\nfrom invalid argument: must be a list\n  (Driver info: chromedriver=99.0.4844.51...),platform=Windows NT 10.0.19044 x86_64)".
This error is due to invalid type of args variable.

**Comment by yesnault** [comment]
merged
