### ISSUE TITLE
Assertions should preserve case

### ISSUE THREAD

**Issue by Thiht** [ovh/venom#527]
I have a JSON with the same key twice, but different case:

```js
{
  "Messages": {
    // ...
  ),
  "messages": "example"
}
```

Because Venom forces to lower the case in assertions, I can't write proper assertions on this JSON, it fails half the time depending on which one Venom chooses :/ 

Can you add a mode to preserve case in assertions?

**Comment by yesnault** [comment]
fixed by https://github.com/ovh/venom/pull/569
