### ISSUE TITLE
support retry of failure

### ISSUE THREAD

**Issue by guoweis-outreach** [ovh/venom#556]
I have been using venom. Since this is real-life, e2e testing, sometimes there is instability in the environment which could cause test failure. Instead of rerunning everything, which is time consuming, I'm hoping we could have a feature to just retry the failed ones up to X time.

if this seems a reasonable idea to you, I'd love to submit a PR for this. Thoughts?

**Comment by guoweis-outreach** [comment]
my test cases have dependency. i.e. i use the output from one test case as input to next one. What I want to retry is the whole test suite, not just a single test case

**Comment by fsamin** [comment]
Hello @guoweis-outreach,
You would like to retry a whole testsuite, or just a testcase ?

**Comment by yesnault** [comment]
I close this issue, it has been inactive for a while. Feel free to reopen if needed.
