### ISSUE TITLE
Skip with variables

### ISSUE THREAD

**Issue by ColinHuang** [ovh/venom#564]
If I use skip with other test step's variables. It will get `error converting YAML to JSON: yaml: line 23: did not find expected key` error.

```
- name: test skip
  skip:
  - {{.AAA.id}} ShouldBeEmpty
```

**Comment by yesnault** [comment]
```
- name: test skip
  skip:
  - {{.AAA.id}} ShouldBeEmpty
```
is not a valid yml. Should be ok with:

```
- name: test skip
  skip:
  - "{{.AAA.id}} ShouldBeEmpty"
```

**Comment by ColinHuang** [comment]
@yesnault  Thanks! Solved my problem. Maybe could added to the readme description.
