### ISSUE TITLE
Assert result.bodyjson on JSON key with spaces

### ISSUE THREAD

**Issue by thcdrt** [ovh/venom#579]
Hello,

I'm trying to make an assertion with http executor with a json with a key with spaces and special characters, json extract:
`{
  "scan_overview": {
    "application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0": {
      "severity": "Medium"
    }
  }
}`

I tried with the following assertion:
`result.bodyjson.scan_overview."application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0".severity ShouldEqual Medium`

But I got the error:
`Testcase "GetVulnerabilityScanReports", step #0: Assertion "result.bodyjson.scan_overview.\"application/vnd.scanner.adapter.vuln.report.harbor+json\\; version=1.0\".severity ShouldEqual Medium" failed. expected: Medium  got: <nil> (clair.yaml:84)`

I don't know if I don't use the right key, or if there is a bug.

Thanks,
Thomas

**Comment by yesnault** [comment]
can you provide a full reproducer if it's still the case with latest release please? We'll reopen this issue.
