### ISSUE TITLE
Improving error debugging (especially in CI)

### ISSUE THREAD

**Issue by mlcdf** [ovh/venom#595]
Hello folks! :)

The `info` keyword is great, but it always print (even if the test is successful).

It would be very useful to have something that only prints on failure. So that when everything is fine, it does not pollute the output and in case of an error, you have enough info to debug (it's especially true when a test fails in a CI pipeline and only in CI).

Currently the workaround is to perform an "dummy" assertion on systemout/systemerr (result.systemout ShouldEqual "") so that when it fails, you get the output.

At first, I was thinking of the new keyword. But maybe a new verbosity level that prints the all `result` in case of a failure would be simpler and a lot more convenient. 

What do you think? I can try to work on a PR :)

On another note: I've been using venom since I joined OVHcloud a few months ago, and I like it very much. It's a great little piece of software :)

**Comment by aabouzaid** [comment]
It would be great to have that.
This change will improve readability a lot and it will be easy to read the output in the CI pipelines at a glance.
