### ISSUE TITLE
Running venon v1.1.0-rc.1 always create a venom.log file even with verbosity = 0

### ISSUE THREAD

**Issue by mlcdf** [ovh/venom#599]
Hi there, 

I'm testing the release candidate, and I have this unexpected behavior: 
- no matter the verbosity level, a venom.log file is always generated
-  the same venom.log file used to be overridden at every run. It's not the case anymore so you quickly get dozens of venom*.log file in your current dir.
```console
[...]
$ ./venom1.1.0 run tests
          [trac] writing venom.9.log
 • Title of TestSuite (tests/deploy.yml)
        • TestCase-with-default-value-exec-cmd-Check-if-exit-code-1 PASS
final status: PASS
$ ./venom1.1.0 run tests
          [trac] writing venom.10.log
 • Title of TestSuite (tests/deploy.yml)
        • TestCase-with-default-value-exec-cmd-Check-if-exit-code-1 PASS
final status: PASS
$ ll venom*log | wc -l
35
```

I tested with the latest stable version (1.0.1),  and it worked as expected:

```console
$ ./venom1.0.1 version
Version venom: v1.0.1
$ ./venom1.0.1 run tests
 • Title of TestSuite (tests/deploy.yml)
        • TestCase-with-default-value-exec-cmd-Check-if-exit-code-1 SUCCESS
$ ./venom1.0.1 run tests
 • Title of TestSuite (tests/deploy.yml)
        • TestCase-with-default-value-exec-cmd-Check-if-exit-code-1 SUCCESS
$ ./venom1.0.1 run tests
 • Title of TestSuite (tests/deploy.yml)
        • TestCase-with-default-value-exec-cmd-Check-if-exit-code-1 SUCCESS
$ ./venom1.0.1 run tests -v
          [trac] writing venom.log
 • Title of TestSuite (tests/deploy.yml)
        • TestCase-with-default-value-exec-cmd-Check-if-exit-code-1 SUCCESS
$ ./venom1.0.1 run tests -v
          [trac] writing venom.log
 • Title of TestSuite (tests/deploy.yml)
        • TestCase-with-default-value-exec-cmd-Check-if-exit-code-1 SUCCESS
$ ./venom1.0.1 run tests -v
          [trac] writing venom.log
 • Title of TestSuite (tests/deploy.yml)
        • TestCase-with-default-value-exec-cmd-Check-if-exit-code-1 SUCCESS
```

**Comment by nqb** [comment]
https://github.com/ovh/venom/issues/441

**Comment by mlcdf** [comment]
Okay so the "write in another file every time" is expected. But still, it should not create a log file when the verbosity level is 0 (unspecified) it think ?

**Comment by yesnault** [comment]
It is an expected behaviour.
When a test fails, it is regularly necessary to check the log file venom.log, without having to relaunch the full test.
On CI/CD environment, we don't care about the file creation as the 'workspace' is often ephemeral. If you run venom outside the ci/cd, you probably need to manage the log file as you want matching the exit code. 
`venom run && rm venom*.log`

**Comment by mlcdf** [comment]
Ok thanks!
