### ISSUE TITLE
Unable to Assert JSON Array

### ISSUE THREAD

**Issue by neilmatthewlott** [ovh/venom#612]
assertions:
          - result.statuscode ShouldEqual 200
          - result.bodyjson ShouldContainKey applyRuleMetadataResults
          - result.bodyjson ShouldHaveLength 1
          - result.bodyjson.applyRuleMetadataResults.applyRuleMetadataResults0 ShouldContainKey domain
          - result.bodyjson.applyRuleMetadataResults0.domain ShouldEqual "258"

"bodyjson": {
   "applyRuleMetadataResults": [
    {
     "domain": "RESULT",
     "metadataKey": "TARGET_FIRMWARE_VERSION_NAME",
     "metadataOperator": "EQUAL",
     "metadataValue": "vafa0.2.39",
     "ruleMetadataId": 372
    },
    {
     "domain": "RESULT",
     "metadataKey": "TARGET_PROFILE_PROFILE_ID_NUMBER",
     "metadataOperator": "EQUAL",
     "metadataValue": "258",
     "ruleMetadataId": 373
    }
   ]
  },

 	• i-applyruleforfastreferencetag
 		• http FAIL
 		  Testcase "i-applyruleforfastreferencetag", step #0-0: Assertion "result.bodyjson.applyRuleMetadataResults.applyRuleMetadataResults0 ShouldContainKey domain" failed. unable to cast <nil> of type <nil> to map[string]interface{} (testsuite.yml:0)
 		  Testcase "i-applyruleforfastreferencetag", step #0-0: Assertion "result.bodyjson.applyRuleMetadataResults0.domain ShouldEqual \"258\"" failed. expected: 258  got: <nil> (testsuite.yml:0)
	  	  [trac] writing docs/automated-testing/venom/results/testsuite.i-applyruleforfastreferencetag.step.0.0.dump.json

What am I missing?

**Comment by antback** [comment]
Hi @neilmatthewlott,

I suffered myself. I think that the problem is that the keys must be lowercase. Try this:

```
      - result.bodyjson.applyrulemetadataresults.applyrulemetadatatesults0 ShouldContainKey domain
      - result.bodyjson.applyrulemetadataresults0.domain ShouldEqual "258"

```

**Comment by neilmatthewlott** [comment]
Thanks
