### ISSUE TITLE
add construct to dump HTTP response to a local file

### ISSUE THREAD

**Issue by guoweis-work** [ovh/venom#624]
I have a large json HTTP response that I want to process in the later step. Do you think it's reasonable to add a construct in http executor to dump the body into a local file? I can submit a PR if you think this is reasonable.

**Comment by guoweis-outreach** [comment]
the alternative is to send this to an output var, and then use script to dump it to a file but with all these quotes, things get wrong pretty quickly

**Comment by yesnault** [comment]
a user executor with exec and curl should be enough for that I think
