### ISSUE TITLE
Disable logs when using go install

### ISSUE THREAD

**Issue by pcriv** [ovh/venom#649]
I wanted to install venom using go install, I was able doing this:

```shell
go install github.com/ovh/venom/cmd/venom@latest
```

But seems that bc is a snapshot version I get logging enabled by default, is there any flag to disable them?

**Comment by yesnault** [comment]
we do not recommand to use venom with a go install command. Btw, some improvement were done on this pr https://github.com/ovh/venom/pull/675 about the verbose flag.
