### ISSUE TITLE
Select Output Log Level

### ISSUE THREAD

**Issue by djloude** [ovh/venom#666]
Possible feature if its not possible now but I want to log tests but do not need all the DEBUG or even INFO messages. This floods my memory and is making venom unusable for my http tests. 

Possible bug if its not intended behavior but it looks like the http test logs use and rewrite parts of the previous http test logs. ex. my first http test logs 18 lines, my second http test logs 49 lines, my third test logs 81 lines and so on. Stopping my testsuite with 9 passed tests results in a log file of 1319 lines! 

My use case:
- running venom from the supported docker image to test ~2017 web pages for status code 200 and execution time < 2 seconds.
- Tried overriding the VENOM_VERBOSE environment variable with VENOM_VERBOSE=0 and VENOM_VERBOSE="".
- Tried to reduce the log file size with ignore_body: true set.

**Comment by yesnault** [comment]
fixed with https://github.com/ovh/venom/pull/675
