### ISSUE TITLE
Stop using a global logger?

### ISSUE THREAD

**Issue by skateinmars** [ovh/venom#692]
Hello,

I have been trying to integrate venom as a library in our tooling, but I have come across issues when trying to run scenarios in parallel

Unfortunately, when calling `InitLogger()` on a venom.Venom struct, the global logrus logger also gets reset and replaced (with the log output file also being overridden).
The obvious solution seems to be adding a logrus field to the Venom struct

Obviously this global logger is used everywhere in code and executors (via the global funcs), so replacing this usage may be time consuming. So the question is, do you believe this work is worth doing to improve the usage of venom as a library?

**Comment by yesnault** [comment]
Hi, if this request is still relevant (sorry for the response time on the subject), can you provide a example of unit test trying using venom as libary please?

Initialy, venom was designed to be used in unit test, this is no longer supported now. But perhaps we can try something to make it works, without impacting all existing logger calls.
