### ISSUE TITLE
Parallel execution of test suites 

### ISSUE THREAD

**Issue by fokion** [ovh/venom#736]
Have the ability to run the test suites in parallel mode by default and introduce a keyword  (for example `parallel`) in test cases that we want to run in parallel.

**Comment by ivan-velasco** [comment]
@fokion There was a PR https://github.com/ovh/venom/pull/299 sometime back to remove this and use the GNU parallel library instead. I have done this for some time now and it works well. 

I do like the idea of have a additional attributes to tell the test runner what to run in parallel. We could extend that list of attributes to have BeforeEach, AfterEach, Before, After, etc like other testing frameworks runners.

**Comment by yesnault** [comment]
Hi, yes, you don't want to add a new parallel mode into venom. You have to do that with something above venom. BeforeEach (testsuite), After, etc.. you have to do that above venom (or use venom to trigger venom). We really don't want to add this  complexity into venom directly

**Comment by fokion** [comment]
#741
