### ISSUE TITLE
FEATURE REQUEST: Skip specific `.yml` or `.yaml` files on blanket `venom run`

### ISSUE THREAD

**Issue by polyphilz** [ovh/venom#740]
I like to run `venom run` from the root dir of my project, but have a whole bunch of other `.yml` and `.yaml` files in there that aren't Venom tests. They still end up in my log output dir though.

Is there existing functionality to ignore these non-Venom test YAML files? If not, would be a great feature - TIA!

**Comment by marcaudefroy** [comment]
Hello!

On our side, we name our venom tests by myTest.venom.yml
And launch CI with  `venom run suite=**/*venom.yml`

**Comment by fokion** [comment]
you can specify a file pattern for example test_.*.yml

**Comment by polyphilz** [comment]
Thanks both, do you know if it's the case that Venom runs all individual `.*.venom.yml` files in parallel if I use the above method? Or is it one after the other?

**Comment by fokion** [comment]
it is sequential at the moment see https://github.com/ovh/venom#run-test-suites-in-a-specific-order and https://github.com/ovh/venom#globstar-support

**Comment by polyphilz** [comment]
Thanks!
