### ISSUE TITLE
Add --var-env [prefix] feature

### ISSUE THREAD

**Issue by ymartin-ovh** [ovh/venom#762]
Hello

With venom before 1.x, we could import any environment variables. For now, it seems to be restricted to those beginning with VENOM_VAR_

It would be interesting to provide a --var-env [prefix1, prefix2, ...] to allow import environment variable beginning with prefixes in the list.

Regards

**Comment by yesnault** [comment]
Hi,

You can use in a exec executor env variables. Example:

```
❯ ./venom run c.yml
 • truc (c.yml)
        • testA PASS
final status: PASS
❯ cat aa.log
foo with a bar here truc
❯ export AA=foo
❯ ./venom run c.yml
 • truc (c.yml)
        • testA PASS
final status: PASS
❯ cat aa.log
foo with a bar here foo
❯ cat c.yml
name: truc
testcases:
- name: testA
  steps:
  - type: exec
    script: echo "foo with a bar here $AA" > aa.log

**Comment by ymartin-ovh** [comment]
Ok thanks.
