### ISSUE TITLE
Documentation update for beta4

### ISSUE THREAD

**Issue by miklosbagi** [ovh/venom#763]
Howdy folks,

I looked up the docs for SQL executor and ran into having `__len__` provided as example for assertions, which I believe is now `__Len__`, here: [README.md](https://github.com/ovh/venom/blob/8e28aedad3bb8c4dacaa6e165cf9370f6136cad0/executors/sql/README.md)

HTH,
mb

**Comment by ivan-velasco** [comment]
That is correct or you can use `ShouldHaveLength`

**Comment by miklosbagi** [comment]
Hey @ivan-velasco, thanks for your reply.

So this is the case now, correct?
- `__len__` fails
- `__Len__` works
- `ShouldHaveLength` works

**Comment by miklosbagi** [comment]
Ah the commit sign... :)
Proposed update in #765

**Comment by yesnault** [comment]
merged
