### ISSUE TITLE
[Question] Is there a way to make authenticated integration tests ?

### ISSUE THREAD

**Issue by NathanNeves** [ovh/venom#783]
Great tool!

Is there a way to test endpoints that require an authentication token? How can I authenticate and pass the authentication token to subsequent tests?

**Comment by yesnault** [comment]
Hi, yes, it's possible as you can inject variable with value from a previous step. It really depends on your usecase, which executor, etc... If it's to test a http webapp, the executor `http` is ok to inject variable as header for example. And if an existing executor is not enough, you should be able to do what you want with the `exec ` executor.
