### ISSUE TITLE
Kafka Executor - client has run out of available brokers to talk to: EOF

### ISSUE THREAD

**Issue by calinDM** [ovh/venom#800]
Venom 1.2.0 fails to connect redpanda kafka broker with the following message:
`step #1-0: Assertion "result.err ShouldBeEmpty" failed. expected 'error instantiate consumer err: kafka: client has run out of available brokers to talk to: EOF' to be empty but it wasn't`

**Example:**
` 
testcases:
  - name: Check that message was sent
    steps:
     - type: kafka
        clientType: consumer
        withAvro: true
        markOffset: true
        timeout: 15
        waitFor: 10
        messageLimit: 1
        groupID: venom-consumer
        addrs:
          - "{{.kafkaBrokerTarget}}"
        schemaRegistryAddr: "{{.kafkaSchemaRegistryURL}}"
        topics:
          - {{.kafkaTopicName}}
        assertions:
          - "result.err ShouldBeEmpty"
          - "result.messages.__len__ ShouldEqual 1"
          - "result.messagesjson.messagesjson0.err ShouldBeEmpty"
          - "result.messagesjson.messagesjson0.value ShouldNotBeEmpty"
`

**Workaround:**

Set _kafkaVersion:"2.0.0"_ as in

` 
testcases:
  - name: Check that message was sent
    steps:
     - type: kafka
        clientType: consumer
        kafkaVersion: "2.0.0"
        withAvro: true
        markOffset: true
        timeout: 15
        waitFor: 10
        messageLimit: 1
        groupID: venom-consumer
        addrs:
          - "{{.kafkaBrokerTarget}}"
        schemaRegistryAddr: "{{.kafkaSchemaRegistryURL}}"
        topics:
          - {{.kafkaTopicName}}
        assertions:
          - "result.err ShouldBeEmpty"
          - "result.messages.__len__ ShouldEqual 1"
          - "result.messagesjson.messagesjson0.err ShouldBeEmpty"
          - "result.messagesjson.messagesjson0.value ShouldNotBeEmpty"
`

**Comment by yesnault** [comment]
yes, kafkaVersion is probably required for you;

"  - kafka_version optional, default is 0.10.2.0"
