### ISSUE TITLE
Customize Html Test Report - extract the Required data from venom log and Report

### ISSUE THREAD

**Issue by ushabkrishna** [ovh/venom#802]
Hi Team

  Can some one help me to get the customized report? 

Currently my project need is to report the tests run with more specific data and log details accurately with links provided if there is a Failure case.

Current venom html report gives the format with text alone without any indentation, how do i make it more UI friendly on the report Section? any documentation?

**Comment by ivan-velasco** [comment]
@ushabkrishna This is the file
https://github.com/ovh/venom/blob/master/venom_output.html

**Comment by ushabkrishna** [comment]
Does Venom has any plugin to support the Reporting?

**Comment by ivan-velasco** [comment]
@ushabkrishna The report above is the template used to generate the html report. If you run a venom testsuite and have the html output enabled (--html-report) it will generate this report. Additionally there is a junit report. More info [here](https://github.com/ovh/venom?tab=readme-ov-file#export-tests-report)

**Comment by yesnault** [comment]
Thank you @ivan-velasco
