### ISSUE TITLE
feat: Variable replacement in `bodyFile` (http executor)

### ISSUE THREAD

**Issue by FabienM** [ovh/venom#82]
At the moment, it's not possible to perform variable replacement with `bodyFile`, which is painful with large dynamic payloads.

**Comment by titpetric** [comment]
I just closed #220 as a duplicate, this is still a valid feature request

**Comment by nqb** [comment]
I'm able to have something similar using following scenario:

bodyfile.json:
```json
{"username":"{{.username}}","password":"admin"}
```
vars.yaml
```
username: overrided
```

Running `venom` like this: `venom run --var-from-file vars.yaml`

`{{.username}}` is replaced by `overrided` in my JSON payload.

**Comment by nqb** [comment]
Ignore my previous comment, issue is present.

**Comment by nqb** [comment]
@fsamin & @yesnault, it would be really nice to have this one in next Venom release.
