### ISSUE TITLE
feat: provide a way to build basic auth from clear user and password

### ISSUE THREAD

**Issue by jbbernat** [ovh/venom#98]
Hi,
To reach rest api protected by basic authentication, we currently use this step : 

- name: BuildBasicAuth
  steps:
  - type: exec
    script: echo -n 'abcd:12345' | base64 | tr -d '\n' | xargs
    extracts:
      result.systemout: '.*'

Problems : 
 - Ugly script command
 - base64 command must be installed on the system which run the test suite.

Could you provide a feature within the http executor to automatically build the Basic Authentication Header with clear user/password creds provided ?

Thanks in advance.

**Comment by yesnault** [comment]
for executor http, it makes sense yes. basicHTTPUser and basic HTTPPassword new attributes.

And, http://masterminds.github.io/sprig/ should be used to allow using a loooot of cool filters in variables (already used by https://gihub.com/ovh/cds ), if you want to use a step script with a on fly base64 encoding

**Comment by jbbernat** [comment]
Thanks for the docs !, issue closed with #100
